// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPqahA2RMVTkJkuqxbN0_7HvJu2p3D04',
    appId: '1:928254103218:web:cb02dc3421eb555d9b83ab',
    messagingSenderId: '928254103218',
    projectId: 'zerowaste-46d54',
    authDomain: 'zerowaste-46d54.firebaseapp.com',
    storageBucket: 'zerowaste-46d54.firebasestorage.app',
    measurementId: 'G-528101LY76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4Ikbn60xAS5WlEZ_qC84n6GJWzr-MGU',
    appId: '1:928254103218:android:6ff83d0cf791a48a9b83ab',
    messagingSenderId: '928254103218',
    projectId: 'zerowaste-46d54',
    storageBucket: 'zerowaste-46d54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPpm0BaW3RdnVy_6HQMLYOJxMbuy0KCxE',
    appId: '1:928254103218:ios:136e395fc0c227699b83ab',
    messagingSenderId: '928254103218',
    projectId: 'zerowaste-46d54',
    storageBucket: 'zerowaste-46d54.firebasestorage.app',
    iosBundleId: 'com.example.zerowaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPpm0BaW3RdnVy_6HQMLYOJxMbuy0KCxE',
    appId: '1:928254103218:ios:136e395fc0c227699b83ab',
    messagingSenderId: '928254103218',
    projectId: 'zerowaste-46d54',
    storageBucket: 'zerowaste-46d54.firebasestorage.app',
    iosBundleId: 'com.example.zerowaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZPqahA2RMVTkJkuqxbN0_7HvJu2p3D04',
    appId: '1:928254103218:web:d87e03ed10f6ee6a9b83ab',
    messagingSenderId: '928254103218',
    projectId: 'zerowaste-46d54',
    authDomain: 'zerowaste-46d54.firebaseapp.com',
    storageBucket: 'zerowaste-46d54.firebasestorage.app',
    measurementId: 'G-WPRRW0VNFD',
  );
}
